### PR TITLE
Add hidden counter for LibreCounter

### PR DESCRIPTION
**Pull request by alexfernandez**
Add a hidden counter for [LibreCounter](https://librecounter.org/): provides free, libre, open stats. GDPR-compliant, no cookies.

Stats will be available at [librecounter.org/durangoretro.com/show](https://librecounter.org/durangoretro.com/show). Example (locally tested):

image

Sample from running site:

image

I have not found a simple way to provide an icon with a link to stats so all users can view them. It would be something like:

```
<a href="https://librecounter.org/referer/show">
<img src="https://librecounter.org/counter.svg" referrerPolicy="unsafe-url" />
</a>
```

Let me know if this can be useful!

### CODE REVIEW

**Comment by zerasul** [comment]
let me check the commits and merge the changes

**Comment by alexfernandez** [comment]
Hi @zerasul ! Any issues I can fix?

**Comment by zerasul** [comment]
Hi @alexfernandez Im on it. Sorry for the delay, in the next days i will check this and try to integrate with librecounter

**Comment by zerasul** [comment]
added librecounter with all the resources

**Comment by alexfernandez** [comment]
:clap: :clap: :clap:  Enjoy your stats at https://librecounter.org/durangoretro.com/show, and let me know if you see anything wrong!

**Pull request merged**
